# Generated by Django 3.0.5 on 2020-04-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200403_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_item',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
